name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  merge_group:
    types:
      - checks_requested
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
        with:
          github_token: ${{ github.token }}
          cache: true
      - name: Setup
        run: mise run bootstrap
      - name: Compile
        run: mise run compile

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
        with:
          github_token: ${{ github.token }}
          cache: true
      - name: Setup
        run: mise run bootstrap
      - name: Run format
        run: mise run format
      - name: Verify no diff
        run: git diff --exit-code
